eight_points_guzzle:
    clients:
        weather:
            # Write here the host where to do requests
            # base_url: "http://target.url"
            base_url: "http://api.apixu.com/"
            options:
                timeout: 30
                http_errors: false

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    Accept: "application/json"
            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~
